### PR TITLE
Ditch Reclutch for Skulpin

### LINKED ISSUE #2: Does not render correctly on OS X
I just tested commit 9b1c006 on Arch with Nightly and it worked without issues.

However, on macOS 10.15 I get a series of errors. It would be nice if this worked well on macOS and I'm happy to be a macOS tester for this editor.

The first error I get reads:
```Rust
error[E0599]: no function or associated item named `from_u32` found for type `char` in the current scope
   --> src/glifparser.rs:203:23
    |
203 |                 char::from_u32(u32::from_str_radix(unicodehex, 16).expect("<unicode> hex not int"))
    |                       ^^^^^^^^ function or associated item not found in `char`
    |
help: you are looking for the module in `std`, not the primitive type
    |
203 |                 std::char::from_u32(u32::from_str_radix(unicodehex, 16).expect("<unicode> hex not int"))
    |                 ^^^^^^^^^^^^^^^^^^^
```
I fixed this but got a few more errors and couldn't get it to build, I might try a PR to get it working, but thought I would post the issue first so you know I'm thinking about it.

Thanks!

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
@aclysma needs to release a version of aclysma/skulpin#63 upstream so I can push this and ditch Reclutch in master.

Closes #2. CC: @eliheuer

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
Oh and sorry @jazzfool this reverts #1 and removes Reclutch...because I want to support Mac, so I took you out of AUTHORS file. Thanks for all your help though, and for recommending this move to Vulkan.

**Comment by eliheuer** [comment]
It works for me on Debian at commit `3c25cea`, but on Mac OS 10.15 I get: 
```
Error during renderer construction: CreateInstanceError(LoadingError(LoadingError(DlOpen { desc: "dlopen(libvulkan.dylib, 2): image not found" })))
```

**Comment by ctrlcctrlv** [comment]
Known issue :) you have to install the Vulkan SDK on OSX for now. If I ever make a binary release that perhaps won't be the case

**Comment by ctrlcctrlv** [comment]
I'll document it once I merge this branch, I have some more work to do on it, hopefully tonight, to get it into a mergeable state~

**Comment by eliheuer** [comment]
Thanks! I'm doing a Twitch stream now looking at the code so far on Debian! 
https://www.twitch.tv/eli_gtl

**Pull request merged**
