### PR TITLE
Add initial CI jobs for Rust build

### PR DESCRIPTION
**Pull request by alerque**
This currently only setup up an Linux build test, I'll submit Windows & Mac additions to this later as I figure out how to get the right toolkit libraries installed on them but this is a good place to start.

There were several things than needed to be fixed & cleaned up regarding the Rust code in general in order to make this happen (for example tracking Cargo's lock file, not naming shell scripts with Rust extensions, using `crate::` namespaces properly, matching Rust's expected syntax, etc.). If you need explanation on why these things needed to be changed let me know.

Note this is currently setup to give a pass to all the warnings, but that's a very significant anti-pattern in the Rust ecosystem. I realize you plan to eliminate these soon so I let it go, but typically with Rust projects CI would be setup so that warnings are errors. Individual cases where the warnings need to be excused can have the suppression and justification in the source code or a config file.

You won't see this run on this PR yet because Github actions requires the config to be in the `master` branch before allowing PR forks to run, but you can see a successful test run [on my fork here](https://github.com/alerque/Qglif/actions/runs/259074284).

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
Thanks so much for the help.

I do indeed know that `-Awarnings` is an anti-pattern. I have a lot of enums floating around that I know I'll need for 1.0, and functions, etc., that I know I'll be using, although currently disabled. Clearly you can see this project is getting quite large&mdash;it's already &approx;3000 lines&mdash;which for me is the largest software project I've worked on as main author.

fb46f16fd88499f65c1f304e89c27ba2c28fdbd3 is the only real surprise for me. I'll merge this tomorrow, it's 3AM where I am, and I have a conflict I'm too tired to sort right now.

**Comment by ctrlcctrlv** [comment]
Actually, I can merge this right now and just move my two bug fixes which I know will conflict into another branch.

Thanks again!

**Comment by alerque** [comment]
Re fb46f16: Without the lock file neither CI nor any other computers other than your own will be able to replicate and verify the build. Just because your system happens to have a specific set of dependency versions doesn't mean the next system that checks this out the next day will have the same set. Even with `==` matching for your direct dependencies (i.e. this project's `Cargo.toml` file), many of the libraries you depend on may themselves request flexible dependencies that allow minor or even major version updates of other libraries. The lock file is where these are tracked. People have the option of building without it and getting the latest allowed dependencies, but the lock file has the known-working/tested set.

Additionally, this provides CI a way to cache the build environment without getting borked between runs. If anything changes in the lock file it does a fresh build, if none of the dependencies (in the entire tree, including dependencies of dependencies) has changed then it can short-circuit and build just your project's code.

The lock file should be updated any time you change package versions in the TOML file and periodically any time you feel like it in between (although there is generally no real good reason to do so unless there is a security bulletin out against something in the tree).

**Comment by ctrlcctrlv** [comment]
Won't this cause a problem as I've been developing on Windows via MSYS2, primarily to make sure I don't break the Windows build but also because my current system has poor hardware support for Linux? ([I broke my real computer while fleeing criminal libel charges in a foreign country. :wink:](https://www.vice.com/en_us/article/y3mqzb/the-philippines-wants-to-arrest-8chan-founder-fredrick-brennan-its-basically-a-death-sentence) Haven't had ability to replace it, should soon.)

Proof of Windows build:

image
image

**Comment by alerque** [comment]
No, the way Rust crate versioning works it won't be a problem that you are developing on one platform and CI is building on another. Eventually we'll cover all platforms in the CI builds which will help catch any mistaken uses of platform specific API calls, but for now carry on with business as usual.

**Comment by ctrlcctrlv** [comment]
Thanks for answering my dumb questions 😇

**Pull request merged**
